name: E2E Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'demos/plaintext-editor/**'
      - 'demos/richtext-editor/**'
      - 'demos/richtext-editor-basic/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'demos/plaintext-editor/**'
      - 'demos/richtext-editor/**'
      - 'demos/richtext-editor-basic/**'

jobs:
  e2e-win:
    runs-on: windows-latest
    strategy:
      #fail-fast: false
      matrix:
        browser: ['chromium', 'firefox']
        editor-mode: ['rich-text', 'plain-text']
        events-mode: ['legacy-events', 'modern-events']
        node-version: [18.18.0]
        exclude:
          - events-mode: 'legacy-events'
            browser: 'firefox'
    env:
      CI: true
      E2E_EDITOR_MODE: ${{ matrix.editor-mode }}
      E2E_EVENTS_MODE: ${{ matrix.events-mode }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm i
        working-directory: ./demos/playground
      - run: pnpm build
        working-directory: ./packages/svelte-lexical
      - name: Download browsers
        run: pnpm playwright install
        working-directory: ./demos/playground
      - run: pnpm test-e2e-ci-${{ matrix.browser }}
        working-directory: ./demos/playground
      - name: Upload Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./demos/playground/playwright-report
          retention-days: 7

  e2e-linux:
    runs-on: ubuntu-latest
    strategy:
      #fail-fast: false
      matrix:
        browser: ['chromium', 'firefox']
        editor-mode: ['rich-text', 'plain-text']
        events-mode: ['modern-events']
        node-version: [18.18.0]
    env:
      CI: true
      E2E_EDITOR_MODE: ${{ matrix.editor-mode }}
      E2E_EVENTS_MODE: ${{ matrix.events-mode }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install required packages
        run: |
          sudo apt-get update
          sudo apt-get install xvfb
      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm i
        working-directory: ./demos/playground
      - run: pnpm build
        working-directory: ./packages/svelte-lexical
      - name: Download browsers
        run: pnpm playwright install
        working-directory: ./demos/playground
      - run: pnpm test-e2e-ci-${{ matrix.browser }}
        working-directory: ./demos/playground
      - name: Upload Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./demos/playground/playwright-report
          retention-days: 7

  e2e-mac:
    runs-on: macos-latest
    strategy:
      #fail-fast: false
      matrix:
        browser: ['chromium', 'firefox', 'webkit']
        editor-mode: ['rich-text', 'plain-text']
        events-mode: ['modern-events']
        node-version: [18.18.0]
    env:
      CI: true
      E2E_EDITOR_MODE: ${{ matrix.editor-mode }}
      E2E_EVENTS_MODE: ${{ matrix.events-mode }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm i
        working-directory: ./demos/playground
      - run: pnpm build
        working-directory: ./packages/svelte-lexical
      - name: Download browsers
        run: pnpm playwright install
        working-directory: ./demos/playground
      - run: pnpm test-e2e-ci-${{ matrix.browser }}
        working-directory: ./demos/playground
      - name: Upload Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./demos/playground/playwright-report
          retention-days: 7

  e2e-collab-win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        browser: ['chromium', 'firefox']
        node-version: [18.18.0]
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm i
        working-directory: ./demos/playground
      - run: pnpm build
        working-directory: ./packages/svelte-lexical
      - name: Download browsers
        run: pnpm playwright install
        working-directory: ./demos/playground
      - run: pnpm test-e2e-collab-ci-${{ matrix.browser }}
        working-directory: ./demos/playground
      - name: Upload Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./demos/playground/playwright-report
          retention-days: 7

  e2e-collab-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: ['chromium', 'firefox']
        node-version: [18.18.0]
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install required packages
        run: |
          sudo apt-get update
          sudo apt-get install xvfb
      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm i
        working-directory: ./demos/playground
      - run: pnpm build
        working-directory: ./packages/svelte-lexical
      - name: Download browsers
        run: pnpm playwright install
        working-directory: ./demos/playground
      - run: pnpm test-e2e-collab-ci-${{ matrix.browser }}
        working-directory: ./demos/playground
      - name: Upload Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./demos/playground/playwright-report
          retention-days: 7

  e2e-collab-mac:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        browser: ['chromium', 'firefox', 'webkit']
        node-version: [18.18.0]
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm i
        working-directory: ./demos/playground
      - run: pnpm build
        working-directory: ./packages/svelte-lexical
      - name: Download browsers
        run: pnpm playwright install
        working-directory: ./demos/playground
      - run: pnpm test-e2e-collab-ci-${{ matrix.browser }}
        working-directory: ./demos/playground
      - name: Upload Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./demos/playground/playwright-report
          retention-days: 7
